# Generated by Django 4.1.4 on 2023-01-26 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('software_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareimage',
            name='supported_devicetypes',
            field=models.ManyToManyField(related_name='software_images', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='softwareimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin'])]),
        ),
    ]
