# Generated by Django 4.1.4 on 2023-01-26 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_manager', '0002_softwareimage_supported_devicetypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin', '.tgz'])]),
        ),
    ]
