# Generated by Django 4.1.4 on 2023-01-26 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_manager', '0003_alter_softwareimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='software-images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin', 'tgz'])]),
        ),
    ]
