# Generated by Django 4.1.4 on 2023-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_manager', '0004_alter_softwareimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareimage',
            name='image_type',
            field=models.CharField(default='junos', max_length=255),
        ),
    ]
